# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

baseurl: /uni
exclude: ['README.md', 'Gemfile']
permalink: pretty

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss

gems: [jekyll-timeago]

jekyll_timeago:
  depth: 1 # Nivel de detalle
  today: 'hoy'
  yesterday: 'ayer'
  tomorrow: 'mañana'
  and: 'y'
  suffix: ''
  prefix: 'hace'
  suffix_future: ''
  prefix_future: 'en'
  years: 'años'
  year: 'año'
  months: 'meses'
  month: 'mes'
  weeks: 'semanas'
  week: 'semana'
  days: 'días'
  day: 'día'